/**
 * @package   Calligraphic Job Board
 * @version   12 September, 2019
 * @author    Calligraphic, LLC http://www.calligraphic.design
 * @copyright Copyright (C) 2019 Calligraphic, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */


/**
 * Region table (states or equivelant entity, e.g. CA)
 */
CREATE TABLE IF NOT EXISTS `#__cajobboard_address_regions` (
  address_region_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Surrogate primary key',
  /* SCHEMA: ItemList for PostalAddress(addressRegion) */
  item_list_element VARCHAR(6) NOT NULL COMMENT 'The abbreviation for the region, e.g. CA',
  /* SCHEMA: Thing */
  `name` VARCHAR(64) NOT NULL COMMENT 'The name of the region, e.g. California',
  PRIMARY KEY (address_region_id)
)
  ENGINE=innoDB
  DEFAULT CHARACTER SET = utf8
  DEFAULT COLLATE = utf8_unicode_ci;


/**
 * Initial regions (states or equivelant entity, e.g. CA)
 */
REPLACE INTO `#__cajobboard_address_regions` (address_region_id, item_list_element, `name`) VALUES
  (1, 'AL', 'COM_CAJOBBOARD_ADDRESS_REGION_ALABAMA'),
  (2, 'AK', 'COM_CAJOBBOARD_ADDRESS_REGION_ALASKA'),
  (3, 'AZ', 'COM_CAJOBBOARD_ADDRESS_REGION_ARIZONA'),
  (4, 'AR', 'COM_CAJOBBOARD_ADDRESS_REGION_ARKANSAS'),
  (5, 'CA', 'COM_CAJOBBOARD_ADDRESS_REGION_CALIFORNIA'),
  (6, 'CO', 'COM_CAJOBBOARD_ADDRESS_REGION_COLORADO'),
  (7, 'CT', 'COM_CAJOBBOARD_ADDRESS_REGION_CONNECTICUT'),
  (8, 'DE', 'COM_CAJOBBOARD_ADDRESS_REGION_DELAWARE'),
  (9, 'FL', 'COM_CAJOBBOARD_ADDRESS_REGION_FLORIDA'),
  (10, 'GA', 'COM_CAJOBBOARD_ADDRESS_REGION_GEORGIA'),
  (11, 'HI', 'COM_CAJOBBOARD_ADDRESS_REGION_HAWAII'),
  (12, 'ID', 'COM_CAJOBBOARD_ADDRESS_REGION_IDAHO'),
  (13, 'IL', 'COM_CAJOBBOARD_ADDRESS_REGION_ILLINOIS'),
  (14, 'IN', 'COM_CAJOBBOARD_ADDRESS_REGION_INDIANA'),
  (15, 'IA', 'COM_CAJOBBOARD_ADDRESS_REGION_IOWA'),
  (16, 'KS', 'COM_CAJOBBOARD_ADDRESS_REGION_KANSAS'),
  (17, 'KY', 'COM_CAJOBBOARD_ADDRESS_REGION_KENTUCKY'),
  (18, 'LA', 'COM_CAJOBBOARD_ADDRESS_REGION_LOUISIANA'),
  (19, 'ME', 'COM_CAJOBBOARD_ADDRESS_REGION_MAINE'),
  (20, 'MD', 'COM_CAJOBBOARD_ADDRESS_REGION_MARYLAND'),
  (21, 'MA', 'COM_CAJOBBOARD_ADDRESS_REGION_MASSACHUSETTS'),
  (22, 'MI', 'COM_CAJOBBOARD_ADDRESS_REGION_MICHIGAN'),
  (23, 'MN', 'COM_CAJOBBOARD_ADDRESS_REGION_MINNESOTA'),
  (24, 'MS', 'COM_CAJOBBOARD_ADDRESS_REGION_MISSISSIPPI'),
  (25, 'MO', 'COM_CAJOBBOARD_ADDRESS_REGION_MISSOURI'),
  (26, 'MT', 'COM_CAJOBBOARD_ADDRESS_REGION_MONTANA'),
  (27, 'NE', 'COM_CAJOBBOARD_ADDRESS_REGION_NEBRASKA'),
  (28, 'NV', 'COM_CAJOBBOARD_ADDRESS_REGION_NEVADA'),
  (29, 'NH', 'COM_CAJOBBOARD_ADDRESS_REGION_NEW_HAMPSHIRE'),
  (30, 'NJ', 'COM_CAJOBBOARD_ADDRESS_REGION_NEW_JERSEY'),
  (31, 'NM', 'COM_CAJOBBOARD_ADDRESS_REGION_NEW_MEXICO'),
  (32, 'NY', 'COM_CAJOBBOARD_ADDRESS_REGION_NEW_YORK'),
  (33, 'NC', 'COM_CAJOBBOARD_ADDRESS_REGION_NORTH_CAROLINA'),
  (34, 'ND', 'COM_CAJOBBOARD_ADDRESS_REGION_NORTH_DAKOTA'),
  (35, 'OH', 'COM_CAJOBBOARD_ADDRESS_REGION_OHIO'),
  (36, 'OK', 'COM_CAJOBBOARD_ADDRESS_REGION_OKLAHOMA'),
  (37, 'OR', 'COM_CAJOBBOARD_ADDRESS_REGION_OREGON'),
  (38, 'PA', 'COM_CAJOBBOARD_ADDRESS_REGION_PENNSYLVANIA'),
  (39, 'RI', 'COM_CAJOBBOARD_ADDRESS_REGION_RHODE_ISLAND'),
  (40, 'SC', 'COM_CAJOBBOARD_ADDRESS_REGION_SOUTH_CAROLINA'),
  (41, 'SD', 'COM_CAJOBBOARD_ADDRESS_REGION_SOUTH_DAKOTA'),
  (42, 'TN', 'COM_CAJOBBOARD_ADDRESS_REGION_TENNESSEE'),
  (43, 'TX', 'COM_CAJOBBOARD_ADDRESS_REGION_TEXAS'),
  (44, 'UT', 'COM_CAJOBBOARD_ADDRESS_REGION_UTAH'),
  (45, 'VT', 'COM_CAJOBBOARD_ADDRESS_REGION_VERMONT'),
  (46, 'VA', 'COM_CAJOBBOARD_ADDRESS_REGION_VIRGINIA'),
  (47, 'WA', 'COM_CAJOBBOARD_ADDRESS_REGION_WASHINGTON'),
  (48, 'WV', 'COM_CAJOBBOARD_ADDRESS_REGION_WEST_VIRGINIA'),
  (49, 'WI', 'COM_CAJOBBOARD_ADDRESS_REGION_WISCONSIN'),
  (50, 'WY', 'COM_CAJOBBOARD_ADDRESS_REGION_WYOMING'),
  (51, 'AS', 'COM_CAJOBBOARD_ADDRESS_REGION_AMERICAN_SAMOA'),
  (52, 'DC', 'COM_CAJOBBOARD_ADDRESS_REGION_DISTRICT_OF_COLUMBIA'),
  (53, 'FM', 'COM_CAJOBBOARD_ADDRESS_REGION_FEDERATED_STATES_OF_MICRONESIA'),
  (54, 'GU', 'COM_CAJOBBOARD_ADDRESS_REGION_GUAM'),
  (55, 'MH', 'COM_CAJOBBOARD_ADDRESS_REGION_MARSHALL_ISLANDS'),
  (56, 'MP', 'COM_CAJOBBOARD_ADDRESS_REGION_NORTHERN_MARIANA_ISLANDS'),
  (57, 'PW', 'COM_CAJOBBOARD_ADDRESS_REGION_PALAU'),
  (58, 'PR', 'COM_CAJOBBOARD_ADDRESS_REGION_PUERTO_RICO'),
  (59, 'VI', 'COM_CAJOBBOARD_ADDRESS_REGION_VIRGIN_ISLANDS');
