/**
 * @package   Calligraphic Job Board
 * @version   0.1 May 1, 2018
 * @author    Calligraphic, LLC http://www.calligraphic.design
 * @copyright Copyright (C) 2018 Calligraphic, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */

/**
 * Email Messages data model SQL
 *
 * Uses schema https://schema.org/EmailMessage
 */
CREATE TABLE IF NOT EXISTS `#__cajobboard_email_messages` (
  email_message_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Surrogate primary key', /* FK to #__cajobboard_ucm(id) */
  slug CHAR(255) NOT NULL COMMENT 'alias for SEF URL',

  /* FOF "magic" fields */
  asset_id	INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Enable record-level access control.', /* FK to #__assets */
  access INT UNSIGNED NOT NULL DEFAULT '1' COMMENT 'The Joomla! view access level.',
  enabled TINYINT NOT NULL DEFAULT '1' COMMENT 'Publish status: -2 for trashed and marked for deletion, -1 for archived, 0 for unpublished, and 1 for published.',
  created_on DATETIME DEFAULT NULL COMMENT 'Timestamp of record creation, auto-filled by save().',
  created_by INT NOT NULL DEFAULT '0' COMMENT 'User ID who created the record, auto-filled by save().',
  modified_on DATETIME DEFAULT NULL COMMENT 'Timestamp of record modification, auto-filled by save(), touch().',
  modified_by INT DEFAULT '0' COMMENT 'User ID who modified the record, auto-filled by save(), touch().',
  locked_on DATETIME DEFAULT NULL COMMENT 'Timestamp of record locking, auto-filled by lock(), unlock().',
  locked_by INT DEFAULT '0' COMMENT 'User ID who locked the record, auto-filled by lock(), unlock().',

  /* Joomla UCM fields, used by Joomla!s UCM when using the FOF ContentHistory behaviour */
  publish_up DATETIME DEFAULT NULL COMMENT 'Date and time to change the state to published, schema.org alias is datePosted.',
  publish_down DATETIME DEFAULT NULL COMMENT 'Date and time to change the state to unpublished.',
  version INT UNSIGNED NOT NULL DEFAULT '1' COMMENT 'Version of this item.',
  ordering INT NOT NULL DEFAULT '0' COMMENT 'Order this record should appear in for sorting.',
  metadata JSON COMMENT 'JSON encoded metadata field for this item.',
  metakey TEXT COMMENT 'Meta keywords for this item.',
  metadesc TEXT COMMENT 'Meta descriptionfor this item.',
  xreference TEXT COMMENT 'A reference to enable linkages to external data sets, used to output a meta tag like FB open graph.',
  params TEXT COMMENT 'JSON encoded parameters for the content item.',
  language CHAR(7) NOT NULL DEFAULT '*' COMMENT 'The language code for the article or * for all languages.',
  cat_id INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Category ID for this content item.',
  hits INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Number of hits the content item has received on the site.',
  featured TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Whether this content item is featured or not.',
  note VARCHAR(255) COMMENT 'A note to save with this answer in the back-end interface.',

  /* SCHEMA: Thing */
  name VARCHAR(255) COMMENT 'Aliased by title property. Used as <h1> header text and page title. The latter can be overridden in params (page_title).',
  description TEXT COMMENT 'Short description of the answer, used for the text shown on social media via shares and search engine results.',

  /* SQL DDL */
  PRIMARY KEY (answer_id)
)
  ENGINE=innoDB
  DEFAULT CHARACTER SET = utf8
  DEFAULT COLLATE = utf8_unicode_ci;


CREATE TABLE `#__akeebasubs_emailtemplates` (
    `akeebasubs_emailtemplate_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `key` varchar(255) NOT NULL DEFAULT '',
    `subscription_level_id` bigint(20) DEFAULT '0',
    `subject` varchar(255) NOT NULL DEFAULT '',
    `body` text,

    PRIMARY KEY (`akeebasubs_emailtemplate_id`)
) DEFAULT COLLATE utf8_general_ci;
            ]]></query>
            <query><![CDATA[


REPLACE INTO `#__akeebasubs_emailtemplates`
(`akeebasubs_emailtemplate_id`, `key`, `subscription_level_id`, `subject`, `body`, `language`, `enabled`, `ordering`, `created_on`, `created_by`, `modified_on`, `modified_by`, `locked_on`, `locked_by`)
VALUES
	(1, 'subscriptionemails_paid', 0, 'Your [LEVEL] subscription at [SITENAME] is now enabled', '<div style=\"background-color: #e0e0e0; padding: 10px 20px;\">\r\n<div style=\"background-color: #f9f9f9; border-radius: 10px; padding: 5px 10px;\">\r\n<p>Hello [FIRSTNAME],</p>\r\n<p>The payment for your [LEVEL] subscription on our site has just been cleared. Your subscription is now activated and will remain active until [PUBLISH_DOWN].</p>\r\n<p><span style=\"line-height: 1.3em;\">We\'d like to remind you that you have registered on our site using the username [USERNAME] and email address [USEREMAIL].</span></p>\r\n<p>You can <a href=\"[MYSUBSURL]\">review the status of all your subscriptions</a> any time on our site.</p>\r\n</div>\r\n<p style=\"font-size: x-small; color: #667;\">You are receiving this automatic email message because you have a subscription in <em>[SITENAME]</em>. <span style=\"line-height: 1.3em;\">Do not reply to this email, it\'s sent from an unmonitored email address.</span></p>\r\n</div>', '*', 1, 1, '2013-01-23 00:00:00', 42, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
	(2, 'subscriptionemails_new_active', 0, 'Your new [LEVEL] subscription at [SITENAME]', '<div style=\"background-color: #e0e0e0; padding: 10px 20px;\">\r\n<div style=\"background-color: #f9f9f9; border-radius: 10px; padding: 5px 10px;\">\r\n<p>Hello [FIRSTNAME],</p>\r\n<p>Your new <span style=\"line-height: 1.3em;\">[LEVEL] </span><span style=\"line-height: 1.3em;\">subscription is now activated and will remain active until [PUBLISH_DOWN].</span></p>\r\n<p><span style=\"line-height: 1.3em;\">We\'d like to remind you that you have registered on our site using the username [USERNAME] and email address [USEREMAIL].</span></p>\r\n<p>You can <a href=\"[MYSUBSURL]\">review the status of all your subscriptions</a> any time on our site.</p>\r\n</div>\r\n<p style=\"font-size: x-small; color: #667;\">You are receiving this automatic email message because you have a subscription in <em>[SITENAME]</em>. <span style=\"line-height: 1.3em;\">Do not reply to this email, it\'s sent from an unmonitored email address.</span></p>\r\n</div>', '*', 1, 2, '2013-01-23 00:00:00', 42, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
	(3, 'subscriptionemails_new_renewal', 0, 'Your [LEVEL] subscription renewal at [SITENAME]', '<div style=\"background-color: #e0e0e0; padding: 10px 20px;\">\r\n<div style=\"background-color: #f9f9f9; border-radius: 10px; padding: 5px 10px;\">\r\n<p>Hello [FIRSTNAME],</p>\r\n<p>Your <span style=\"line-height: 1.3em;\">[LEVEL] </span><span style=\"line-height: 1.3em;\">subscription has been renewed. The renewed subscription will be activated on [PUBLISH_UP] and remain active until [PUBLISH_DOWN].</span></p>\r\n<p><span style=\"line-height: 1.3em;\">We\'d like to remind you that you have registered on our site using the username [USERNAME] and email address [USEREMAIL].</span></p>\r\n<p>You can <a href=\"[MYSUBSURL]\">review the status of all your subscriptions</a> any time on our site.</p>\r\n</div>\r\n<p style=\"font-size: x-small; color: #667;\">You are receiving this automatic email message because you have a subscription in <em>[SITENAME]</em>. <span style=\"line-height: 1.3em;\">Do not reply to this email, it\'s sent from an unmonitored email address.</span></p>\r\n</div>', '*', 1, 3, '2013-01-23 00:00:00', 42, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
	(4, 'subscriptionemails_new_pending', 0, 'Your new [LEVEL] subscription at [SITENAME] is being processed', '<div style=\"background-color: #e0e0e0; padding: 10px 20px;\">\r\n<div style=\"background-color: #f9f9f9; border-radius: 10px; padding: 5px 10px;\">\r\n<p>Hello [FIRSTNAME],</p>\r\n<p>The payment for your new or renewed <span style=\"line-height: 1.3em;\">[LEVEL] </span><span style=\"line-height: 1.3em;\">subscription is currently being processed. When the payment is cleared we will send you a new email. </span><span style=\"line-height: 1.3em;\">Please note that on some occasions it may take 2 to 7 business days for the payment to be cleared. This time period is outside of our control and is mainly due to restrictions imposed by your bank or the payment processor company.</span></p>\r\n<p><span style=\"line-height: 1.3em;\">We\'d like to remind you that you have registered on our site using the username [USERNAME] and email address [USEREMAIL].</span></p>\r\n<p>You can <a href=\"[MYSUBSURL]\">review the status of all your subscriptions</a> any time on our site.</p>\r\n</div>\r\n<p style=\"font-size: x-small; color: #667;\">You are receiving this automatic email message because you have a subscription in <em>[SITENAME]</em>. <span style=\"line-height: 1.3em;\">Do not reply to this email, it\'s sent from an unmonitored email address.</span></p>\r\n</div>', '*', 1, 4, '2013-01-23 00:00:00', 42, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
	(5, 'subscriptionemails_cancelled_new', 0, 'Your new [LEVEL] subscription at [SITENAME] could not be processed', '<div style=\"background-color: #e0e0e0; padding: 10px 20px;\">\r\n<div style=\"background-color: #f9f9f9; border-radius: 10px; padding: 5px 10px;\">\r\n<p>Hello [FIRSTNAME],</p>\r\n<p>The payment processor declined the payment for your new or renewed <span style=\"line-height: 1.3em;\">[LEVEL] </span><span style=\"line-height: 1.3em;\">subscription</span><span style=\"line-height: 1.3em;\">. Please revisit our site and retry subscribing using the same username and email address. You may want to select a different means of payment, for example a different credit card. We apologise for the inconvenience</span></p>\r\n<p><span style=\"line-height: 1.3em;\">We\'d like to remind you that you have registered on our site using the username [USERNAME] and email address [USEREMAIL].</span></p>\r\n<p>You can <a href=\"[MYSUBSURL]\">review the status of all your subscriptions</a> any time on our site.</p>\r\n</div>\r\n<p style=\"font-size: x-small; color: #667;\">You are receiving this automatic email message because you to tried to subscribe to <em>[SITENAME]</em>. <span style=\"line-height: 1.3em;\">Do not reply to this email, it\'s sent from an unmonitored email address.</span></p>\r\n</div>', '*', 1, 5, '2013-01-23 00:00:00', 42, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
	(6, 'subscriptionemails_cancelled_existing', 0, 'Your [LEVEL] subscription at [SITENAME] was cancelled', '<div style=\"background-color: #e0e0e0; padding: 10px 20px;\">\r\n<div style=\"background-color: #f9f9f9; border-radius: 10px; padding: 5px 10px;\">\r\n<p>Hello [FIRSTNAME],</p>\r\n<p>The payment for your <span style=\"line-height: 1.3em;\">[LEVEL] </span><span style=\"line-height: 1.3em;\">subscription was cancelled by our payment processor or refunded at your request</span><span style=\"line-height: 1.3em;\">.</span></p>\r\n<p><span style=\"line-height: 1.3em;\">If you believe you are receiving this message in error and would like to remain subscribed to our site, please visit our site, log in with your username and password and retry subscribing. You may want to select a different means of payment, for example a different credit card. We apologise for the inconvenience</span></p>\r\n<p><span style=\"line-height: 1.3em;\">We\'d like to remind you that you have registered on our site using the username [USERNAME] and email address [USEREMAIL].</span></p>\r\n<p>You can <a href=\"[MYSUBSURL]\">review the status of all your subscriptions</a> any time on our site.</p>\r\n</div>\r\n<p style=\"font-size: x-small; color: #667;\">You are receiving this automatic email message because you had a subscription at <em>[SITENAME]</em>. Do not reply to this email, it\'s sent from an unmonitored email address.</p>\r\n</div>', '*', 1, 6, '2013-01-23 00:00:00', 42, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
	(7, 'subscriptionemails_expired', 0, 'Your [LEVEL] subscription at [SITENAME] has expired', '<div style=\"background-color: #e0e0e0; padding: 10px 20px;\">\r\n<div style=\"background-color: #f9f9f9; border-radius: 10px; padding: 5px 10px;\">\r\n<p>Hello [FIRSTNAME],</p>\r\n<p>Your <span style=\"line-height: 1.3em;\">[LEVEL] </span><span style=\"line-height: 1.3em;\">subscription on our site has expired</span><span style=\"line-height: 1.3em;\">. If you want to renew it </span><a href=\"[MYSUBSURL]\" style=\"line-height: 1.3em;\">please visit the subscriptions status page on our site</a> and click on the \"Renew\" button to the right of the expired subscription.</p>\r\n<p><span style=\"line-height: 1.3em;\"><span style=\"line-height: 1.3em;\">We\'d like to remind you that you have registered on our site using the username [USERNAME] and email address [USEREMAIL].</span></span></p>\r\n<p>You can <a href=\"[MYSUBSURL]\">review the status of all your subscriptions</a> any time on our site.</p>\r\n</div>\r\n<p style=\"font-size: x-small; color: #667;\">You are receiving this automatic email message because you had a subscription at <em>[SITENAME]</em>. Do not reply to this email, it\'s sent from an unmonitored email address.</p>\r\n</div>', '*', 1, 7, '2013-01-23 00:00:00', 42, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
	(8, 'subscriptionemails_published', 0, 'Your renewed [LEVEL] subscription at [SITENAME] has been activated', '<div style=\"background-color: #e0e0e0; padding: 10px 20px;\">\r\n<div style=\"background-color: #f9f9f9; border-radius: 10px; padding: 5px 10px;\">\r\n<p>Hello [FIRSTNAME],</p>\r\n<p>Your <span style=\"line-height: 1.3em;\">[LEVEL] </span><span style=\"line-height: 1.3em;\">subscription renewal on our site has been activated</span><span style=\"line-height: 1.3em;\">. It will remain active until [PUBLISH_DOWN].</span></p>\r\n<p><span style=\"line-height: 1.3em;\">We\'d like to remind you that you have registered on our site using the username [USERNAME] and email address [USEREMAIL].</span></p>\r\n<p>You can <a href=\"[MYSUBSURL]\">review the status of all your subscriptions</a> any time on our site.</p>\r\n</div>\r\n<p style=\"font-size: x-small; color: #667;\">You are receiving this automatic email message because you have a subscription at <em>[SITENAME]</em>. Do not reply to this email, it\'s sent from an unmonitored email address.</p>\r\n</div>', '*', 1, 8, '2013-01-23 00:00:00', 42, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
	(9, 'subscriptionemails_generic', 0, 'Your [LEVEL] subscription at [SITENAME] has been updated', '<div style=\"background-color: #e0e0e0; padding: 10px 20px;\">\r\n<div style=\"background-color: #f9f9f9; border-radius: 10px; padding: 5px 10px;\">\r\n<p>Hello [FIRSTNAME],</p>\r\n<p>Your <span style=\"line-height: 1.3em;\">[LEVEL] </span><span style=\"line-height: 1.3em;\">subscription on our site has been modified. Its new details are:</span></p>\r\n<table width=\"100%\" border=\"0\" cellspacing=\"2\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td width=\"25%\"><strong>Username</strong></td>\r\n<td>[USERNAME] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Subscription type</strong></td>\r\n<td>[LEVEL] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Subscription status</strong></td>\r\n<td>[ENABLED] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Payment status</strong></td>\r\n<td>[PAYSTATE] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Valid From</strong></td>\r\n<td>[PUBLISH_UP]</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Valid To</strong></td>\r\n<td>[PUBLISH_DOWN] </td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p><span style=\"line-height: 1.3em;\"><span style=\"line-height: 1.3em;\">You can </span><a href=\"[MYSUBSURL]\" style=\"line-height: 1.3em;\">review the status of all your subscriptions</a><span style=\"line-height: 1.3em;\"> any time on our site.</span></span></p>\r\n</div>\r\n<p style=\"font-size: x-small; color: #667;\">You are receiving this automatic email message because you have a subscription at <em>[SITENAME]</em>. Do not reply to this email, it\'s sent from an unmonitored email address.</p>\r\n</div>', '*', 1, 9, '2013-01-23 00:00:00', 42, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
	(10, 'asexpirationnotify_first', 0, 'Your [LEVEL] subscription on [SITENAME] will expire soon', '<div style=\"background-color: #e0e0e0; padding: 10px 20px;\">\r\n<div style=\"background-color: #f9f9f9; border-radius: 10px; padding: 5px 10px;\">\r\n<p>Hello [FIRSTNAME],</p>\r\n<p>Your [LEVEL] subscription with the following details is going to expire soon:</p>\r\n<table width=\"100%\" border=\"0\" cellspacing=\"2\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td width=\"25%\"><strong>Username</strong></td>\r\n<td>[USERNAME] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Subscription type</strong></td>\r\n<td>[LEVEL] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Subscription status</strong></td>\r\n<td>[ENABLED] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Payment status</strong></td>\r\n<td>[PAYSTATE] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Valid From</strong></td>\r\n<td>[PUBLISH_UP]</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Valid To</strong></td>\r\n<td>[PUBLISH_DOWN] </td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p><span style=\"line-height: 1.3em;\"><span style=\"line-height: 1.3em;\"><span style=\"line-height: 1.3em;\">You can login any time on our site to </span><a href=\"[MYSUBSURL]\" style=\"line-height: 1.3em;\">review the status of all your subscriptions</a><span style=\"line-height: 1.3em;\"> and renew your expiring one.</span></span></span></p>\r\n<p><span style=\"line-height: 1.3em;\">We\'d like to remind you that you have registered on our site using the username [USERNAME] and email address [USEREMAIL].</span></p>\r\n</div>\r\n<p style=\"font-size: x-small; color: #667;\">You are receiving this automatic email message because you have a subscription in <em>[SITENAME]</em>. <span style=\"line-height: 1.3em;\">Do not reply to this email, it\'s sent from an unmonitored email address.</span></p>\r\n</div>', '*', 1, 10, '2013-01-23 00:00:00', 42, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
	(11, 'asexpirationnotify_second', 0, 'Your [LEVEL] subscription on [SITENAME] is about to expire', '<div style=\"background-color: #e0e0e0; padding: 10px 20px;\">\r\n<div style=\"background-color: #f9f9f9; border-radius: 10px; padding: 5px 10px;\">\r\n<p>Hello [FIRSTNAME],</p>\r\n<p>Your [LEVEL] subscription with the following details is going to expire very soon:</p>\r\n<table width=\"100%\" border=\"0\" cellspacing=\"2\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td width=\"25%\"><strong>Username</strong></td>\r\n<td>[USERNAME] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Subscription type</strong></td>\r\n<td>[LEVEL] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Subscription status</strong></td>\r\n<td>[ENABLED] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Payment status</strong></td>\r\n<td>[PAYSTATE] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Valid From</strong></td>\r\n<td>[PUBLISH_UP]</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Valid To</strong></td>\r\n<td>[PUBLISH_DOWN] </td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p><span style=\"line-height: 1.3em;\"><span style=\"line-height: 1.3em;\"><span style=\"line-height: 1.3em;\">You can login any time on our site to </span><a href=\"[MYSUBSURL]\" style=\"line-height: 1.3em;\">review the status of all your subscriptions</a><span style=\"line-height: 1.3em;\"> and renew your expiring one.</span></span></span></p>\r\n<p> </p>\r\n<p><span style=\"line-height: 1.3em;\">We\'d like to remind you that you have registered on our site using the username [USERNAME] and email address [USEREMAIL].</span></p>\r\n</div>\r\n<p style=\"font-size: x-small; color: #667;\">You are receiving this automatic email message because you have a subscription in <em>[SITENAME]</em>. <span style=\"line-height: 1.3em;\">Do not reply to this email, it\'s sent from an unmonitored email address.</span></p>\r\n</div>', '*', 1, 11, '2013-01-23 00:00:00', 42, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
	(12, 'asexpirationnotify_after', 0, 'Your expired subscription on [SITENAME]', '<div style=\"background-color: #e0e0e0; padding: 10px 20px;\">\r\n<div style=\"background-color: #f9f9f9; border-radius: 10px; padding: 5px 10px;\">\r\n<p>Hello [FIRSTNAME],</p>\r\n<p>We are contacting you to remind you that your subscription on [SITENAME] with the following details has already expired:</p>\r\n<table width=\"100%\" border=\"0\" cellspacing=\"2\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td width=\"25%\"><strong>Username</strong></td>\r\n<td>[USERNAME] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Subscription type</strong></td>\r\n<td>[LEVEL] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Subscription status</strong></td>\r\n<td>[ENABLED] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Payment status</strong></td>\r\n<td>[PAYSTATE] </td>\r\n</tr>\r\n<tr>\r\n<td><strong>Valid From</strong></td>\r\n<td>[PUBLISH_UP]</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Valid To</strong></td>\r\n<td>[PUBLISH_DOWN] </td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p><span><span><span>You can login any time on our site and renew your expired subscription. Renewing your subscription is very easy! You just have to go to the</span></span></span><span style=\"line-height: 1.3em;\"> </span><a href=\"[MYSUBSURL]\" style=\"line-height: 1.3em;\">subscriptions overview</a><span style=\"line-height: 1.3em;\"> page</span><span style=\"line-height: 1.3em;\"> and click on the Renew link.</span></p>\r\n<p><span style=\"line-height: 1.3em;\">We\'d like to remind you that you have registered on our site using the username [USERNAME] and email address [USEREMAIL].</span></p>\r\n</div>\r\n<p style=\"font-size: x-small; color: #667;\">You are receiving this automatic email message because you have a subscription in <em>[SITENAME]</em>. <span style=\"line-height: 1.3em;\">Do not reply to this email, it\'s sent from an unmonitored email address.</span></p>\r\n</div>', '*', 1, 12, '2013-01-23 00:00:00', 42, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0)
;
