/**
 * @package   Calligraphic Job Board
 * @version   0.1 May 1, 2018
 * @author    Calligraphic, LLC http://www.calligraphic.design
 * @copyright Copyright (C) 2018 Calligraphic, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */

/**
 * Days of week table
 */
CREATE TABLE IF NOT EXISTS `#__cajobboard_day_of_week` (
  /* SCHEMA: https://schema.org/DayOfWeek */
  day CHAR(16) NOT NULL,
  PRIMARY KEY (day)
)
  ENGINE=innoDB
  DEFAULT CHARACTER SET = utf8
  DEFAULT COLLATE = utf8_unicode_ci;

 /**
 * Region table (states or equivelant entity, e.g. CA)
 */
CREATE TABLE IF NOT EXISTS `#__cajobboard_address_regions` (
  address_region_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Surrogate primary key',
  /* SCHEMA: ItemList for PostalAddress(addressRegion) */
  item_list_element VARCHAR(6) NOT NULL COMMENT 'The abbreviation for the region, e.g. CA',
  /* SCHEMA: Thing */
  `name` VARCHAR(64) NOT NULL COMMENT 'The name of the region, e.g. California',
  PRIMARY KEY (address_region_id)
)
  ENGINE=innoDB
  DEFAULT CHARACTER SET = utf8
  DEFAULT COLLATE = utf8_unicode_ci;

/**
 * Initial days of the week
 */
INSERT INTO `#__cajobboard_day_of_week` (day) VALUES
  ('Monday'),
  ('Tuesday'),
  ('Wednesday'),
  ('Thursday'),
  ('Friday'),
  ('Saturday'),
  ('Sunday'),
  ('Weekdays'),
  ('Weekends'),
  ('PublicHolidays');

/**
 * Initial regions (states or equivelant entity, e.g. CA)
 */
INSERT INTO `#__cajobboard_address_regions` (item_list_element, `name`) VALUES
    ('AL', 'COM_CAJOBBOARD_ADDRESS_REGION_ALABAMA'),
  ('AK', 'COM_CAJOBBOARD_ADDRESS_REGION_ALASKA'),
  ('AZ', 'COM_CAJOBBOARD_ADDRESS_REGION_ARIZONA'),
  ('AR', 'COM_CAJOBBOARD_ADDRESS_REGION_ARKANSAS'),
  ('CA', 'COM_CAJOBBOARD_ADDRESS_REGION_CALIFORNIA'),
  ('CO', 'COM_CAJOBBOARD_ADDRESS_REGION_COLORADO'),
  ('CT', 'COM_CAJOBBOARD_ADDRESS_REGION_CONNECTICUT'),
  ('DE', 'COM_CAJOBBOARD_ADDRESS_REGION_DELAWARE'),
  ('FL', 'COM_CAJOBBOARD_ADDRESS_REGION_FLORIDA'),
  ('GA', 'COM_CAJOBBOARD_ADDRESS_REGION_GEORGIA'),
  ('HI', 'COM_CAJOBBOARD_ADDRESS_REGION_HAWAII'),
  ('ID', 'COM_CAJOBBOARD_ADDRESS_REGION_IDAHO'),
  ('IL', 'COM_CAJOBBOARD_ADDRESS_REGION_ILLINOIS'),
  ('IN', 'COM_CAJOBBOARD_ADDRESS_REGION_INDIANA'),
  ('IA', 'COM_CAJOBBOARD_ADDRESS_REGION_IOWA'),
  ('KS', 'COM_CAJOBBOARD_ADDRESS_REGION_KANSAS'),
  ('KY', 'COM_CAJOBBOARD_ADDRESS_REGION_KENTUCKY'),
  ('LA', 'COM_CAJOBBOARD_ADDRESS_REGION_LOUISIANA'),
  ('ME', 'COM_CAJOBBOARD_ADDRESS_REGION_MAINE'),
  ('MD', 'COM_CAJOBBOARD_ADDRESS_REGION_MARYLAND'),
  ('MA', 'COM_CAJOBBOARD_ADDRESS_REGION_MASSACHUSETTS'),
  ('MI', 'COM_CAJOBBOARD_ADDRESS_REGION_MICHIGAN'),
  ('MN', 'COM_CAJOBBOARD_ADDRESS_REGION_MINNESOTA'),
  ('MS', 'COM_CAJOBBOARD_ADDRESS_REGION_MISSISSIPPI'),
  ('MO', 'COM_CAJOBBOARD_ADDRESS_REGION_MISSOURI'),
  ('MT', 'COM_CAJOBBOARD_ADDRESS_REGION_MONTANA'),
  ('NE', 'COM_CAJOBBOARD_ADDRESS_REGION_NEBRASKA'),
  ('NV', 'COM_CAJOBBOARD_ADDRESS_REGION_NEVADA'),
  ('NH', 'COM_CAJOBBOARD_ADDRESS_REGION_NEW_HAMPSHIRE'),
  ('NJ', 'COM_CAJOBBOARD_ADDRESS_REGION_NEW_JERSEY'),
  ('NM', 'COM_CAJOBBOARD_ADDRESS_REGION_NEW_MEXICO'),
  ('NY', 'COM_CAJOBBOARD_ADDRESS_REGION_NEW_YORK'),
  ('NC', 'COM_CAJOBBOARD_ADDRESS_REGION_NORTH_CAROLINA'),
  ('ND', 'COM_CAJOBBOARD_ADDRESS_REGION_NORTH_DAKOTA'),
  ('OH', 'COM_CAJOBBOARD_ADDRESS_REGION_OHIO'),
  ('OK', 'COM_CAJOBBOARD_ADDRESS_REGION_OKLAHOMA'),
  ('OR', 'COM_CAJOBBOARD_ADDRESS_REGION_OREGON'),
  ('PA', 'COM_CAJOBBOARD_ADDRESS_REGION_PENNSYLVANIA'),
  ('RI', 'COM_CAJOBBOARD_ADDRESS_REGION_RHODE_ISLAND'),
  ('SC', 'COM_CAJOBBOARD_ADDRESS_REGION_SOUTH_CAROLINA'),
  ('SD', 'COM_CAJOBBOARD_ADDRESS_REGION_SOUTH_DAKOTA'),
  ('TN', 'COM_CAJOBBOARD_ADDRESS_REGION_TENNESSEE'),
  ('TX', 'COM_CAJOBBOARD_ADDRESS_REGION_TEXAS'),
  ('UT', 'COM_CAJOBBOARD_ADDRESS_REGION_UTAH'),
  ('VT', 'COM_CAJOBBOARD_ADDRESS_REGION_VERMONT'),
  ('VA', 'COM_CAJOBBOARD_ADDRESS_REGION_VIRGINIA'),
  ('WA', 'COM_CAJOBBOARD_ADDRESS_REGION_WASHINGTON'),
  ('WV', 'COM_CAJOBBOARD_ADDRESS_REGION_WEST_VIRGINIA'),
  ('WI', 'COM_CAJOBBOARD_ADDRESS_REGION_WISCONSIN'),
  ('WY', 'COM_CAJOBBOARD_ADDRESS_REGION_WYOMING'),
  ('AS', 'COM_CAJOBBOARD_ADDRESS_REGION_AMERICAN_SAMOA'),
  ('DC', 'COM_CAJOBBOARD_ADDRESS_REGION_DISTRICT_OF_COLUMBIA'),
  ('FM', 'COM_CAJOBBOARD_ADDRESS_REGION_FEDERATED_STATES_OF_MICRONESIA'),
  ('GU', 'COM_CAJOBBOARD_ADDRESS_REGION_GUAM'),
  ('MH', 'COM_CAJOBBOARD_ADDRESS_REGION_MARSHALL_ISLANDS'),
  ('MP', 'COM_CAJOBBOARD_ADDRESS_REGION_NORTHERN_MARIANA_ISLANDS'),
  ('PW', 'COM_CAJOBBOARD_ADDRESS_REGION_PALAU'),
  ('PR', 'COM_CAJOBBOARD_ADDRESS_REGION_PUERTO_RICO'),
  ('VI', 'COM_CAJOBBOARD_ADDRESS_REGION_VIRGIN_ISLANDS');
