/**
 * Sample Organization table data
 */

INSERT INTO `#__cajobboard_organizations` (
  slug,
  legal_name,
  email,
  telephone,
  fax_number,
  number_of_employees,
  location,
  logo,
  diversity_policy,
  aggregate_rating,
  member_of,
  parent_organization,
  name,
  disambiguating_description,
  description,
  url,
  image,
  role_name,
  organization_type
) VALUES
(
  'elite-property-management',
  'Elite Property Management, Inc.',
  'admin@elite-property.test',
  '1-800-555-1212',
  '702-555-0000',
  '5000',
  '1',
  '8',
  '8',
  '1',
  '1',
  '1',
  'Elite Property West',
  'Elite can be the best job of your life!',
  'Founded in 1995, Elite Property Management is a family owned and operated business with headquarters in Virginia Beach, Virginia.',
  'http://elite-property.test',
  '1',
  '1',
  '3'
),
(
  'action-property-management',
  'Action Property Management, LLC',
  'admin@action-property.text',
  '1-800-222-1234',
  '702-555-7890',
  '40',
  '2',
  '9',
  '9',
  '2',
  '2',
  '2',
  'Action Property',
  'Action Property is a Gold-Star employer. Join us!',
  'At Action Property, exceptional, personalized living comes full of amenities with none of the stress of homeownership. We do it through the programs we offer, a commitment to local neighborhoods and innovative green living opportunities. Our award-winning apartments are managed and staffed by award-winning teams. Residents rent with us, and stay with us, because our life\'s work is helping people feel at home, over and over again. Building and maintaining strong relationships with our residents, employees, investors and partners matters to us. We\'ve got the depth of experience and financial foundation to provide stability and peace of mind to our renters.',
  'http://action-property.text',
  '2',
  '1',
  '4'
);
