/**
 * Sample User Profiles table data
 */

INSERT INTO `#__user_profiles` (user_id, profile_key, profile_value) VALUES
  ('131', 'cajobboard.description', 'I’ve learned I don’t know anything.  Have also learned that people will pay for what I know.  Life is good.'),
  ('131', 'cajobboard.main_entity_of_page', 'http://www.centurycommunications.com'),
  ('131', 'cajobboard.given_name', 'Tom'),
  ('131', 'cajobboard.additional_name', 'Yuki'),
  ('131', 'cajobboard.family_name', 'Whobrey'),
  ('131', 'cajobboard.telephone', '602-277-4385'),
  ('131', 'cajobboard.fax_number', '602-953-6360'),
  ('131', 'cajobboard.job_title', 'HR Director'),
  ('131', 'cajobboard.address__street_address', '73 State Road 434 E	Phoenix	'),
  ('131', 'cajobboard.address__locality', 'Maricopa'),
  ('131', 'cajobboard.address__postal_code', '85013'),
  ('131', 'cajobboard.address__address_country', 'US'),
  ('131', 'cajobboard.role_name', 'Employer'),
  ('131', 'cajobboard.image', '3'),
  ('131', 'cajobboard.address_region', '3'),
  ('131', 'cajobboard.geo', '8'),
  ('131', 'cajobboard.worksFor', '1'),
  ('132', 'cajobboard.description', 'Living one day at a time, with a fresh baked cookie. Okay.  And with a coffee.  And maybe some chocolate. But I promise to take my vitamins.'),
  ('132', 'cajobboard.main_entity_of_page', 'http://www.boltonwilburesq.com'),
  ('132', 'cajobboard.given_name', 'Janice'),
  ('132', 'cajobboard.additional_name', 'Fletcher'),
  ('132', 'cajobboard.family_name', 'Flosi'),
  ('132', 'cajobboard.telephone', '931-313-9635'),
  ('132', 'cajobboard.fax_number', '931-235-7959'),
  ('132', 'cajobboard.job_title', 'Human Resources Manager'),
  ('132', 'cajobboard.address__street_address', '69734 E Carrillo St'),
  ('132', 'cajobboard.address__locality', 'Warren'),
  ('132', 'cajobboard.address__postal_code', '37110'),
  ('132', 'cajobboard.address__address_country', 'US'),
  ('132', 'cajobboard.role_name', 'Employer'),
  ('132', 'cajobboard.image', '4'),
  ('132', 'cajobboard.address_region', '42'),
  ('132', 'cajobboard.geo', '7'),
  ('132', 'cajobboard.worksFor', '2'),
  ('133', 'cajobboard.description', 'Nerdfighter.  Determined dreamer.  Has ambitions to be crazy cat lady if marrying various celebrity crushes proves impossible.'),
  ('133', 'cajobboard.main_entity_of_page', 'http://www.tmbyxbeecompanypc.com'),
  ('133', 'cajobboard.given_name', 'Tim'),
  ('133', 'cajobboard.additional_name', 'Gladys'),
  ('133', 'cajobboard.family_name', 'Rim'),
  ('133', 'cajobboard.telephone', '414-661-9598'),
  ('133', 'cajobboard.fax_number', '414-377-2880'),
  ('133', 'cajobboard.job_title', 'Maintenance Technician'),
  ('133', 'cajobboard.address__street_address', '322 New Horizon Blvd'),
  ('133', 'cajobboard.address__locality', 'Milwaukee'),
  ('133', 'cajobboard.address__postal_code', '53207'),
  ('133', 'cajobboard.address__address_country', 'US'),
  ('133', 'cajobboard.role_name', 'Job Seeker'),
  ('133', 'cajobboard.image', '5'),
  ('133', 'cajobboard.address_region', '49'),
  ('133', 'cajobboard.geo', '1'),
  ('133', 'cajobboard.worksFor', 'NULL'),
  ('134', 'cajobboard.description', 'Insert pretentious crap about myself here.'),
  ('134', 'cajobboard.main_entity_of_page', 'http://www.farmersinsurancegroup.com'),
  ('134', 'cajobboard.given_name', 'Susan'),
  ('134', 'cajobboard.additional_name', 'Bette'),
  ('134', 'cajobboard.family_name', 'Nicka'),
  ('134', 'cajobboard.telephone', '313-288-7937'),
  ('134', 'cajobboard.fax_number', '313-341-4470'),
  ('134', 'cajobboard.job_title', 'Leasing Agent'),
  ('134', 'cajobboard.address__street_address', '1 State Route 27 Taylor'),
  ('134', 'cajobboard.address__locality', 'Wayne'),
  ('134', 'cajobboard.address__postal_code', '48180'),
  ('134', 'cajobboard.address__address_country', 'US'),
  ('134', 'cajobboard.role_name', 'Job Seeker'),
  ('134', 'cajobboard.image', '6'),
  ('134', 'cajobboard.address_region', '22'),
  ('134', 'cajobboard.geo', '2'),
  ('134', 'cajobboard.worksFor', 'NULL'),
  ('135', 'cajobboard.description', '90% of your problems can be solved by marketing.  Solving the other 10% just requires good procrastination skills.'),
  ('135', 'cajobboard.main_entity_of_page', 'http://www.postboxservicesplus.com'),
  ('135', 'cajobboard.given_name', 'Tony'),
  ('135', 'cajobboard.additional_name', 'Meaghan'),
  ('135', 'cajobboard.family_name', 'Garufi'),
  ('135', 'cajobboard.telephone', '815-828-2147'),
  ('135', 'cajobboard.fax_number', '815-426-5657'),
  ('135', 'cajobboard.job_title', 'Recruitment Specialist'),
  ('135', 'cajobboard.address__street_address', '394 Manchester Blvd	Rockford'),
  ('135', 'cajobboard.address__locality', 'Winnebago'),
  ('135', 'cajobboard.address__postal_code', '61109	'),
  ('135', 'cajobboard.address__address_country', 'US'),
  ('135', 'cajobboard.role_name', 'Recruiter'),
  ('135', 'cajobboard.image', '7'),
  ('135', 'cajobboard.address_region', '13'),
  ('135', 'cajobboard.geo', '3'),
  ('135', 'cajobboard.worksFor', '1'),
  ('136', 'cajobboard.description', 'I’m really a giant cupcake.  Afraid of roller coasters and dry ice'),
  ('136', 'cajobboard.main_entity_of_page', 'http://www.sportenart.com'),
  ('136', 'cajobboard.given_name', 'Amy'),
  ('136', 'cajobboard.additional_name', 'Mattie'),
  ('136', 'cajobboard.family_name', 'Poquette'),
  ('136', 'cajobboard.telephone', '610-545-3615'),
  ('136', 'cajobboard.fax_number', '610-492-4643'),
  ('136', 'cajobboard.job_title', 'Director of Recruiting'),
  ('136', 'cajobboard.address__street_address', '6 S 33rd St	Aston'),
  ('136', 'cajobboard.address__locality', 'Delaware'),
  ('136', 'cajobboard.address__postal_code', '19014'),
  ('136', 'cajobboard.address__address_country', 'US'),
  ('136', 'cajobboard.role_name', 'Recruiter'),
  ('136', 'cajobboard.image', 'NULL'),
  ('136', 'cajobboard.address_region', '38'),
  ('136', 'cajobboard.geo', '4'),
  ('136', 'cajobboard.worksFor', '2'),
  ('137', 'cajobboard.description', 'Coffee-Drinker, eReader Addict, Mom, Blogger.  I’m very busy and important'),
  ('137', 'cajobboard.main_entity_of_page', 'http://www.internationaleyeletsinc.com'),
  ('137', 'cajobboard.given_name', 'Mike'),
  ('137', 'cajobboard.additional_name', 'Allene'),
  ('137', 'cajobboard.family_name', 'Iturbide'),
  ('137', 'cajobboard.telephone', '913-413-4604'),
  ('137', 'cajobboard.fax_number', '913-645-8918'),
  ('137', 'cajobboard.job_title', 'Secretary'),
  ('137', 'cajobboard.address__street_address', '7219 Woodfield Rd	Overland Park'),
  ('137', 'cajobboard.address__locality', 'Johnson'),
  ('137', 'cajobboard.address__postal_code', '66204'),
  ('137', 'cajobboard.address__address_country', 'US'),
  ('137', 'cajobboard.role_name', 'Connector'),
  ('137', 'cajobboard.image', 'NULL'),
  ('137', 'cajobboard.address_region', '16'),
  ('137', 'cajobboard.geo', '5'),
  ('137', 'cajobboard.worksFor', '1'),
  ('138', 'cajobboard.description', 'Buddy, can you paradigm?'),
  ('138', 'cajobboard.main_entity_of_page', 'http://www.rapidtradingintl.com'),
  ('138', 'cajobboard.given_name', 'Julie'),
  ('138', 'cajobboard.additional_name', 'Alisha'),
  ('138', 'cajobboard.family_name', 'Slusarski'),
  ('138', 'cajobboard.telephone', '907-231-4722'),
  ('138', 'cajobboard.fax_number', '907-335-6568'),
  ('138', 'cajobboard.job_title', 'Trainer'),
  ('138', 'cajobboard.address__street_address', '1048 Main St'),
  ('138', 'cajobboard.address__locality', 'Fairbanks'),
  ('138', 'cajobboard.address__postal_code', '99708'),
  ('138', 'cajobboard.address__address_country', 'US'),
  ('138', 'cajobboard.role_name', 'Connector'),
  ('138', 'cajobboard.image', 'NULL'),
  ('138', 'cajobboard.address_region', '2'),
  ('138', 'cajobboard.geo', '6'),
  ('138', 'cajobboard.worksFor', '2');
